name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Achievements
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          repositories_affiliations: >-
            owner, collaborator
          plugin_achievements: yes
          plugin_achievements_ignored: >-
            gister, forker, stargazer, follower, automator, reviewer
      - name: Midly interesting facts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.facts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          repositories_affiliations: >-
            owner, collaborator
          plugin_habits: yes
          plugin_habits_from: 500
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_charts: no
          config_timezone: America/Vancouver
      - name: Comment reactions
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.reactions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          repositories_affiliations: >-
            owner, collaborator
          plugin_reactions: yes
          plugin_reactions_limit: 200
          plugin_reactions_details: percentage
      - name: Most Used Languages
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          repositories_affiliations: >-
            owner, collaborator
          plugin_languages: yes
          plugin_languages_ignored: yaml, unity, gosum, gopkg, gomod, dotenv, meta
          plugin_languages_limit: 0
          plugin_languages_other: no
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, lines, percentage
          plugin_languages_analysis_timeout: 120
          plugin_languages_analysis_timeout_repositories: 30
          plugin_languages_recent_load: 2000
          plugin_languages_recent_days: 365
          plugin_languages_indepth: yes
          plugin_languages_categories: markup, programming, data, prose
